blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://github.com/pkyanam/omarchy-4-pi/discussions/categories/ideas
    about: Suggest a new feature, change to existing feature, or other ideas in Discussions.
  - name: Support
    url: https://github.com/pkyanam/omarchy-4-pi/discussions/categories/q-a
    about: Ask for Raspberry Pi port help in Discussions. Issues should be used for reproducible bugs.
